name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  dev-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

  merge-to-master:
    runs-on: ubuntu-latest
    needs: dev-branches
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fast-forward master branch
        run: |
          git fetch origin
          git checkout master
          git merge --ff-only dev
          git push origin master

  failure-recovery:
    runs-on: ubuntu-latest
    needs: dev-branches
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure dev branch is up to date
        run: |
          git fetch origin
          git checkout dev
          git pull origin dev

      - name: Create failure branch
        run: |
          failure_branch="failure/$(date +%s)"
          git branch $failure_branch
          git push origin $failure_branch
          git reset --hard HEAD@{1}
          git push origin dev --force
