name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  test_and_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover tests
      - name: Merge to merge-to-master
        if: success()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b merge-to-master
          git merge --no-ff dev -m "Merge dev into merge-to-master"
          git push origin merge-to-master