name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run tests
        run: |
          python -m unittest discover -s tests -v

  merge-to-master:
    runs-on: ubuntu-latest
    needs: dev-branch
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Attempt merge
        run: |
          git checkout master
          git pull origin master
          git merge origin/dev || echo "Merge conflict detected"
        continue-on-error: true

      - name: Check for conflicts
        run: |
          if git status | grep -q 'You have unmerged paths'; then
            echo "Merge conflicts detected. Manual intervention required."
            git status
            exit 1
          else
            git push origin master
          fi

