name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/ --verbose

  merge-to-master:
    runs-on: ubuntu-latest
    needs: dev-branch
    if: ${{ success() }}  # Assurez-vous que les tests sont réussis avant d'exécuter le merge
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if there are changes to merge
        run: |
          git fetch origin
          git diff --quiet origin/master..dev || echo "There are changes to merge"  # Vérifie les différences entre dev et master

      - name: Merge dev into master
        run: |
          git checkout master
          git merge dev --ff-only
          git push origin master

  failure-recovery:
    runs-on: ubuntu-latest
    needs: dev-branch
    if: ${{ failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create failure branch
        run: |
          FAILURE_BRANCH="failure/$(date +%s)"
          git fetch origin
          git branch -D failure || true
          git push origin --delete failure || true
          git checkout dev
          git branch $FAILURE_BRANCH
          git push origin $FAILURE_BRANCH
