name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests -v

      - name: Save failed commit to 'failure' branch
        if: ${{ failure() }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git checkout -b failure || git checkout failure
          git merge dev --no-commit || true  # Merge sans valider pour éviter de briser la branche failure
          git commit -am "Save failed state from dev branch" || true
          git push origin failure
